packages:
  - core
  - adapters/*
  - publishers/*
  - config

onlyBuiltDependencies:
  - better-sqlite3
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2

catalog:
  typescript: 5.9.3
  vitest: ^4.0.16
  "@types/node": ^25.0.3

