packages:
  - core
  - adapters/*
  - publishers/*
  - config

catalog:
  typescript: 5.9.3
  tsdown: ^0.18.1
  
  vitest: ^4.0.16
  testcontainers: ^10.2.1
  
  "@biomejs/biome": ^2.3.10
  "@eslint/js": ^9.39.2
  eslint: ^9.39.2
  eslint-plugin-import: 2.32.0
  eslint-plugin-vitest: 0.5.4
  typescript-eslint: ^8.50.0
  
  vite-tsconfig-paths: ^6.0.3
  
  "@types/node": ^25.0.3
  
  ioredis: ^5.8.2

onlyBuiltDependencies:
  - better-sqlite3
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
