packages:
  - packages/core
  - packages/saga
  - packages/adapters/*
  - packages/publishers/*
  - config

catalog:
  '@biomejs/biome': ^2.3.10
  '@eslint/js': ^9.39.2
  '@types/node': ^25.0.3
  eslint: ^9.39.2
  eslint-plugin-import: 2.32.0
  eslint-plugin-vitest: 0.5.4
  ioredis: ^5.8.2
  testcontainers: ^11.10.0
  tsdown: ^0.18.2
  typescript: 5.9.3
  typescript-eslint: ^8.50.0
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16

onlyBuiltDependencies:
  - better-sqlite3
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
